# DimigoOn Jekyll 사이트 설정
title: DimigoOn
email: imchan0325@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  디미고 온라인 알고리즘 학습 플랫폼. 단계별 알고리즘 학습과 정보 올림피아드 문제 풀이를 제공합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dimigoon.github.io" # the base hostname & protocol for your site

# 소셜 미디어 설정
twitter_username: 
github_username: dimigoon
instagram_username: dimigo_on

# Google 서비스 설정
google_analytics: # GA 추적 ID (예: G-XXXXXXXXXX)
google_site_verification: cwJUoykt64F1jfXkUeA6rVGyCqlrhp3efpLJh-DWzOk # Search Console 확인 코드 (google-site-verification 메타 태그의 content 값)

# 빌드 설정
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
  parse_block_html: true
  parse_span_html: true

# Jekyll 플러그인
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 컬렉션 설정
collections:
  algorithms:
    output: true
    permalink: /:collection/:name/
  solutions:
    output: true
    permalink: /solutions/:path/

# 기본값 설정
defaults:
  - scope:
      path: ""
      type: "algorithms"
    values:
      layout: "algorithm"
  - scope:
      path: ""
      type: "solutions"
    values:
      layout: "solution"

# Sass 설정
sass:
  sass_dir: _sass
  style: compressed

# 빌드에서 제외할 파일들
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
  - .git/
  - .gitignore
  - tools/
  - REFACTORING_GUIDE.md

# 페이지 포함 설정
include:
  - _pages
